name: date_time_picker
description: A Flutter widget to display a date time form field to show a date or clock dialog.
version: 3.0.2
homepage: https://github.com/m3uzz/date_time_picker

environment:
  sdk: ">=3.11.1 <4.0.0"
  flutter: ">=3.41.3"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
